### PR TITLE
Add a wrapper that exposes OCL properties as natural JavaScript objects

### PR DESCRIPTION
**Pull request by mcasperson**
This library is useful for parsing the OCL that defines config-as-code steps. However, the raw AST object requires a lot of drilling down into `LiteralNodes` and `Tokens` to get the desired values.

The `parseSteps` function wraps the AST  object with a Proxy that allows the OCL tree to be accessed as natural JavaScript objects. This allows the end user to parse the OCL and inspect it for the purpose of automating PRs or other policy checks.

### CODE REVIEW

**Comment by zentron** [comment]
Thanks @mcasperson , What is the use case for this addition?
Given that we may update the OCL schema in future i'm conservative on anything else that we might impact from changing how things work.

**Comment by mcasperson** [comment]
@zentron The main use case is to support teams that need to enforce checks during pull requests of cac enabled projects. For example, if the first step of a process should be a manual intervention step, a check durind a PR should enforce the action type of the first step. This can only be done today with a manual review of the ocl during a PR, or using this library to parse the ocl and perform an automated check.

**Comment by mcasperson** [comment]
Based in the discussion [here](https://octopusdeploy.slack.com/archives/C033W4273/p1699297831110919) (internal link) it seems that the CaC OCL syntax will remain a subset of HCL, but we do expect the content of the files to change, and possible the locations where they are saved.

This PR will still allow end users to query an OCL file from JavaScript for the purposes of validating PRs and other automated Gitops based tasks. But we will have to warn people that any scripts will have to change with updates to the content of the OCL files.

**Review by zentron — APPROVED** [review]
Given that this is largely just a OCL parser and not tied to the actual data model of OCL, then this seems reasonable to merge. 

I will though pass any issues raised your way in the short term @mcasperson  😄

**Comment by mcasperson** [comment]
> I will though pass any issues raised your way in the short term @mcasperson 😄

No problem, we're happy to address any concerns rasied by customers.

**Pull request merged**
